9 calculate images overlays
centralelyon/ntt pull request #10
Opened 2023-09-07 10:47 UTC by faroukmiled

I added a function to overlay two images (https://github.com/centralelyon/ntt/blob/9-calculate-images-overlays/src/ntt/frames/overlay_two_images.py)

I added an example and a test (checking if the two input frames have the same shape).

https://github.com/centralelyon/ntt/blob/9-calculate-images-overlays/examples/ex_overlay_images.py
https://github.com/centralelyon/ntt/blob/9-calculate-images-overlays/tests/test_overlay_images.py

Tests passed successfully

2023-09-07 10:49 UTC, faroukmiled commented
@romsson  I made a pull request. Can you check it before committing to main?

2023-09-11 13:58 UTC, romsson requested changes

2023-09-13 09:04 UTC, faroukmiled commented on examples/ex_overlay_images.py
> +    path_frames="./samples"
resolved

2023-09-13 12:07 UTC, faroukmiled commented on src/ntt/videos/video_fusion.py
> +def video_fusion_image(list_videos_path,video_out):
resolved

2023-09-13 13:56 UTC, faroukmiled commented on src/ntt/frames/overlay_two_images.py
> +    overlayed_frame = cv2.addWeighted(frame1, 0.5, frame2, 0.5, 0)
resolved

2023-09-13 13:56 UTC, faroukmiled commented on src/ntt/videos/video_fusion.py
> +    opacities = [0.5 for i in range(len(list_videos_path))]  # Opacity values for each video
resolved

2023-09-13 14:00 UTC, faroukmiled commented on examples/ex_video_fusion.py
resolved.

added test_custom function to test_overlay_images.py. The function generates two empty frames and a frame with a green rectangle in the middle (reference frame)
Then we overlay the first empty frame with the frame with a rectangle with 50% opacity for each (we obtain overlayed_image1).
We perform the same operation for the second empty frame  (we obtain overlayed_image2).
We then overlay  overlayed_image1 and overlayed_image2 with 50% opacity for each and we compare the result with reference frame (we should obtain the same result).

2023-09-13 14:45 UTC, merged